default_agent: agentic_rag_agent
agents:
  agentic_rag_agent:
    name: agentic_rag_agent
    entrypoint: C:/Agentic-Rag-and-BedRock-Agentrcore/Agent/main.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: C:\Agentic-Rag-and-BedRock-Agentrcore
    aws:
      execution_role: arn:aws:iam::868138719839:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-263992e66a
      execution_role_auto_create: false
      account: '868138719839'
      region: us-east-1
      ecr_repository: 868138719839.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-agentic_rag_agent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: agentic_rag_agent-idoA1L63Um
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:868138719839:runtime/agentic_rag_agent-idoA1L63Um
      agent_session_id: 1faf8fd1-4534-4816-986a-d389353dcc42
    codebuild:
      project_name: bedrock-agentcore-agentic_rag_agent-builder
      execution_role: arn:aws:iam::868138719839:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-263992e66a
      source_bucket: bedrock-agentcore-codebuild-sources-868138719839-us-east-1
    memory:
      mode: STM_AND_LTM
      memory_id: agentic_rag_agent_mem-zQv8X76V5W
      memory_arn: null
      memory_name: agentic_rag_agent_memory
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
